version: "3.4"
services:
  getjenny-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    restart: unless-stopped
    command: [ elasticsearch, -E, network.host=0.0.0.0, -E, node.max_local_storage_nodes=3 ]
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    environment:
      - MAX_LOCKED_MEMORY=unlimited
    deploy:
      endpoint_mode: dnsrr
      replicas: 3

  starchat:
    image: java:8
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: ["/starchat/scripts/utils/wait-for-it.sh", "https://getjenny-es", "9200", "10", "/starchat/bin/starchat"]
    volumes:
      - ./starchat:/starchat
    ports:
      - "8888:8888"
      - "8443:8443"
    deploy:
      replicas: 4
